export const SERVICE_AREAS = [
  {
    id: 'kisii',
    name: 'Kisii County',
    description: 'As our home base, we provide comprehensive exhauster and transport services throughout Kisii County. From Kisii Town to rural areas, our fleet reaches every corner of the county.',
    coverageAreas: [
      'Kisii Town',
      'Ogembo',
      'Keroka',
      'Nyamache',
      'Suneka',
      'Marani',
      'And all surrounding areas',
    ],
    services: [
      'Septic tank emptying',
      'Grease trap cleaning',
      'Residential moving',
      'Commercial transport',
      'Emergency services (24/7)',
    ],
    highlights: [
      'Local knowledge and expertise',
      'Fastest response times',
      'Main service hub',
      'Full fleet availability',
    ],
  },
  {
    id: 'nyamira',
    name: 'Nyamira County',
    description: 'Serving Nyamira County with the same dedication and professionalism. Our modern fleet and experienced team ensure quality service delivery across the county.',
    coverageAreas: [
      'Nyamira Town',
      'Keroka',
      'Nyansiongo',
      'Manga',
      'Borabu',
      'And all surrounding areas',
    ],
    services: [
      'Septic tank emptying',
      'Grease trap cleaning',
      'Residential moving',
      'Commercial transport',
      'Emergency services (24/7)',
    ],
    highlights: [
      'Local knowledge and expertise',
      'Fast response times',
      'Competitive pricing',
      'Professional service',
    ],
  },
  {
    id: 'migori',
    name: 'Migori County',
    description: 'Extending our services to Migori County with reliable exhauster and transport solutions. We understand the unique needs of the region and deliver accordingly.',
    coverageAreas: [
      'Migori Town',
      'Rongo',
      'Awendo',
      'Kilgoris',
      'Lolgorian',
      'Kehancha',
      'Uriri',
      'Suna',
      'And all surrounding areas',
    ],
    services: [
      'Septic tank emptying',
      'Grease trap cleaning',
      'Residential moving',
      'Commercial transport',
      'Emergency services (24/7)',
    ],
    highlights: [
      'Timely service delivery',
      'Modern equipment',
      'Trained personnel',
      'Customer satisfaction guaranteed',
    ],
  },
  {
    id: 'homabay',
    name: 'Homabay County',
    description: 'Comprehensive services across Homabay County, from the lakeside to inland areas. Our team is equipped to handle all your exhauster and transport needs.',
    coverageAreas: [
      'Homabay Town',
      'Mbita',
      'Ndhiwa',
      'Rachuonyo',
      'Rangwe',
      'And all surrounding areas',
    ],
    services: [
      'Septic tank emptying',
      'Grease trap cleaning',
      'Residential moving',
      'Commercial transport',
      'Emergency services (24/7)',
    ],
    highlights: [
      '24/7 availability',
      'Emergency response',
      'Affordable rates',
      'Professional team',
    ],
  },
] as const;

export const COUNTY_NAMES = ['Kisii', 'Nyamira', 'Migori', 'Homabay', 'Kilgoris', 'Lolgorian', 'Kehancha', 'Awendo'] as const;
